variable "PrivateKey" {}
variable "CompanyID" {}
variable "ApplicationName" {}
variable "CoralogixEndpoint" {}
variable "AlertsPrivateKey" {}
variable "SubnetId" {}
variable "SSHKey" {}
variable "ConfigS3BucketName" {}
variable "MgmtNicSecurityGroupID" {}
variable "PacketsS3BucketRequired" {}
variable "PacketsS3Bucket" {}
variable "tags" {}
variable "STASize" {}
variable "STALifecycle" {}
variable "ElasticIpRequired" {}
variable "WazuhRequired" {}
variable "STA-size-pool" {}
variable "SpotPrice" {}
variable "DiskSize" {}
variable "EncryptDisk" {}
variable "DiskType" {}
variable "CreateCoralogixResources" {}

module "STA" {
  source = "https://coralogix-integrations.s3-eu-west-1.amazonaws.com/cloud-security/terraform/snowbit-sta.template.tgz"

  PrivateKey               = var.PrivateKey
  CompanyID                = var.CompanyID
  ApplicationName          = var.ApplicationName
  CoralogixEndpoint        = var.CoralogixEndpoint
  AlertsPrivateKey         = var.AlertsPrivateKey
  SubnetId                 = var.SubnetId
  SSHKey                   = var.SSHKey
  ConfigS3BucketName       = var.ConfigS3BucketName
  MgmtNicSecurityGroupID   = var.MgmtNicSecurityGroupID
  PacketsS3BucketRequired  = var.PacketsS3BucketRequired
  PacketsS3Bucket          = var.PacketsS3Bucket
  tags                     = var.tags
  STASize                  = var.STASize
  STALifecycle             = var.STALifecycle
  ElasticIpRequired        = var.ElasticIpRequired
  WazuhRequired            = var.WazuhRequired
  STA-size-pool            = var.STA-size-pool
  SpotPrice                = var.SpotPrice
  DiskSize                 = var.DiskSize
  DiskType                 = var.DiskType
  EncryptDisk              = var.EncryptDisk
  CreateCoralogixResources = var.CreateCoralogixResources
}